events {
    worker_connections 4096;
}

http {
    upstream masters {
        least_conn;
        server master1:7000;
        #server master2:7000;

        # mark master as down after 3 failures
        # try next master automatically
    }

    server {
        listen 80;

        location / {
            proxy_pass http://masters;
            proxy_next_upstream error timeout;
            proxy_connect_timeout 5s;
            proxy_read_timeout 9000s;
        }
    }
}